[package]
name = "safa-buffer-pool-example"
authors = ["Alexandre Fromantin <oalexandrefromantin@gmail.com>"]
edition = "2024"
description = "Safa-buffer-pool example"
license = "MIT"

[dependencies]
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
safa-buffer-pool = {path = "../"}